/* === kurama.aeris.upgrade.js — AERIS Cosmic Planetary Explorer bridge =====
   Strategic integration layer loaded last. It keeps the courier game intact and
   adds the AERIS scanner UX, orbital planet profiles, live moons/rings/weather,
   dark spiral theme lab, Vajra/mandala/void/iris lenses, and codex/TriForge hooks.
   No external assets; everything is procedural, single-file and reversible. === */
(function(){
  'use strict';
  const AERIS_PLANETS=[
    {id:'syran',name:'SYRAN',sub:'The Poison Pearl',realm:'Acid Ocean',sector:'AERIS-02',dist:'0.45 PX',atm:'98% Acid',temp:'+312 °C',gravity:'1.05 g',moons:1,mag:'None',diff:'Extreme',score:9,tilt:.12,spin:.25,fx:'acid',weather:'acid rain · pressure lightning · turquoise cyclones',terrain:'liquid-ammonia oceans, jade continents, clouded pressure ridges',pal:['#052160','#083b91','#13c9e8','#7ef0d2','#71c26b','#f4ffe7'],missions:[['☁','VAPOR DRIFT','Float a probe through the temperate acid layer.'],['△','CRUSH ASCENT','Climb pressure ridges before the searing front rolls in.'],['◎','STATIC SURVEY','Catalogue upper-atmosphere electrical forms.']],moonsData:[['Prime',1.46,.22,16,'#f3f0e7']]},
    {id:'aerilion',name:'AERILION',sub:'The Cradle',realm:'Aqua Biosphere',sector:'AERIS-03',dist:'1.00 PX',atm:'Oxidized Mix',temp:'+18 °C',gravity:'1.00 g',moons:3,mag:'Strong',diff:'Easy',score:2,tilt:-.32,spin:.18,fx:'aqua',weather:'calm rain bands · reef glow · polar aurora',terrain:'bioluminescent reefs, violet flora, pearl cloud forests',pal:['#00a6d8','#83eff0','#fff0d3','#d69aff','#f8ffff','#0878bd'],missions:[['◉','ABYSSAL SWEEP','Document glowing reefs from low orbit.'],['△','AETHER RUN','Chase plasma light shows above the magnetic poles.'],['◌','CELENE HOP','Stage a quick visit to the shattered moon.']],moonsData:[['Zyphos',1.68,.25,22,'#efe9c8'],['Kharon IX',1.34,.16,14,'#f8f8f8'],['Vortyxo',1.18,.14,8,'#c49d5f']]},
    {id:'doth',name:'DOTH',sub:'The Crimson Wastes',realm:'Terraformer Desert',sector:'AERIS-04',dist:'1.80 PX',atm:'Dense Smog',temp:'-45 °C',gravity:'0.42 g',moons:1,mag:'Very Weak',diff:'Hard',score:6,tilt:.72,spin:.19,fx:'dust',weather:'red dust · orange heat plumes · smog curtains',terrain:'rust steppes, canyon grids, ancient engine scars',pal:['#b94822','#df8e56','#74b8b0','#efe4c4','#332a25','#f5c277'],missions:[['△','ENGINE RUN','Traverse the ancient artificial canyon systems.'],['⌁','APEX CLIMB','Summit the largest dormant terraformer module.'],['◎','CORE SCAN','Search for active power beneath the southern hemisphere.']],moonsData:[['Elyndra',1.45,.24,24,'#efe9c3']],rings:true,ring:'#e6d7b0'},
    {id:'vorantis',name:'VORANTIS',sub:'The Storm Sovereign',realm:'Gas Giant',sector:'AERIS-05',dist:'6.50 PX',atm:'Turbulent H₂',temp:'-120 °C',gravity:'3.12 g',moons:4,mag:'Extreme',diff:'Extreme',score:9,tilt:-.04,spin:.32,fx:'storm',weather:'hypercane belts · plasma lightning · violent moon tides',terrain:'banded ammonia decks, cyclone belts, floating pressure shelves',pal:['#f7efcf','#e6a24d','#b7652c','#9fc7af','#fff9e8','#62e7db'],missions:[['◎','VORTEX DIVE','Plunge a probe into the centuries-old hypercane.'],['↧','GLACIA DRILL','Pierce an ice moon to sample hidden dark ocean.'],['◉','IGNIS MAP','Catalogue plasma eruptions on the violent moon.']],moonsData:[['Tesseron',1.5,.2,18,'#e8e1c2'],['Virellion',1.9,.19,26,'#e5d6a2'],['Noctyra',1.72,.14,22,'#cbc0a4'],['Dravion',1.3,.16,8,'#d6b17a']]},
    {id:'nyxia',name:'NYXIA',sub:'The Crowned Jewel',realm:'Noble-Gas Aurora',sector:'AERIS-06',dist:'11.2 PX',atm:'Noble Gases',temp:'-155 °C',gravity:'1.25 g',moons:2,mag:'Very Strong',diff:'Moderate',score:5,tilt:.42,spin:.21,fx:'nyxia',weather:'aurora crowns · crystalline rings · star-matter storms',terrain:'red-black basins, white vortex crown, blue anomaly eyes',pal:['#24030b','#e3172d','#011837','#124b86','#fff8f2','#b98945'],missions:[['◎','HALO DIVE','Navigate crystalline rings to study anomaly shards.'],['◉','AURA SURVEY','Land in northern basins and analyze exotic liquids.'],['☍','RESONANCE WATCH','Track harmonic vibrations through the atmosphere.']],moonsData:[['Orphelios',1.65,.2,14,'#bb8a4e'],['Xanthea',1.3,.14,8,'#d7c6a0']],rings:true,ring:'#7aa7ff'},
    {id:'glacies',name:'GLACIES',sub:'The Silent Warden',realm:'Frozen Ether',sector:'AERIS-07',dist:'22.4 PX',atm:'Frozen Ether',temp:'-210 °C',gravity:'0.92 g',moons:3,mag:'Fractured',diff:'Hard',score:6,tilt:1.1,spin:.16,fx:'ice',weather:'ghost rings · dust-thin bands · fractured poles',terrain:'cyan glacial basins, red ice cliffs, pale storm shells',pal:['#16413f','#67d8c3','#f4fff8','#f2554b','#9de8df','#ffd0c9'],missions:[['◉','AXIAL ORBIT','Map the bizarre fractured magnetic poles.'],['☄','DUST TRACE','Profile the barely-visible ghost rings up close.'],['◎','VERA SURVEY','Catalogue the unnatural geometric cliffs.']],moonsData:[['Umbrix',1.28,.16,8,'#bbbcc5'],['Mlyrith',1.85,.2,22,'#d4c875'],['Caelora',1.55,.18,14,'#b98945']],rings:true,ring:'#dffcff'},
    {id:'obsidium',name:'OBSIDIUM',sub:'The Dyson Veil',realm:'Cyber Shell',sector:'AERIS-09',dist:'42.0 PX',atm:'Photon Lattice',temp:'+41 °C',gravity:'1.40 g',moons:0,mag:'Artificial',diff:'Mythic',score:10,tilt:.06,spin:.12,fx:'cyber',weather:'blue highways · mirror panels · luminous core pulses',terrain:'Dyson shell plates, ring highways, data-lit continents',pal:['#010817','#0b2a5c','#35ccff','#78f5ff','#ffbc45','#ffffff'],missions:[['✦','CORE IGNITION','Map the artificial star in the equatorial shell.'],['⌬','MIRROR WALK','Align orbital reflectors along the Dyson ring.'],['⌁','PHOTON THREAD','Trace a live data highway around the globe.']],moonsData:[],rings:true,ring:'#5edcff'},
    {id:'vajris',name:'VAJRIS',sub:'The Resonant Axis',realm:'Vajra Field',sector:'AERIS-10',dist:'108.0 PX',atm:'Sacred Plasma',temp:'0 °C',gravity:'1.08 g',moons:2,mag:'Polar Lock',diff:'Legendary',score:8,tilt:0,spin:.08,fx:'vajra',weather:'white-gold hourglass · eight-petal route field · sun/moon discs',terrain:'mandala ridges, polar resonance towers, glyph-lit valleys',pal:['#050507','#fff7d6','#ffd36d','#ffffff','#bfb7a0','#9b7cf6'],missions:[['☼','SUN DISC','Tune the upper male-pole resonance crown.'],['☾','MOON DISC','Balance the lower female-pole return field.'],['✥','EIGHT PETAL','Open the route wheel to all fabled realms.']],moonsData:[['Surya',1.48,.18,18,'#ffd36d'],['Chandra',1.32,.16,11,'#dfe8ff']],rings:true,ring:'#fff0a5'}
  ];
  const AERIS_THEMES=[
    ['violet','Violet Spiral','#b84cff','#65e6ff','#ff7be8','#03020a'],['emerald','Emerald Orbit','#19ffbb','#73ffd7','#c6ff77','#020d0a'],['cyan','Cyan Nebula','#35ccff','#78f5ff','#b4e2ff','#03101e'],['gold','Golden Horizon','#ffbd4d','#ffed9f','#ff8f31','#130b02'],['red','Red Velocity','#ff385f','#ff7c8f','#ffb14d','#120208'],['blue','Blue Core','#3179ff','#72c7ff','#b9e8ff','#020713'],['teal','Teal Wave','#12e6df','#77ffef','#b7fff5','#021315'],['purple','Purple Cosmos','#9d59ff','#e48cff','#68e8ff','#090214'],['mono','Monochrome','#ffffff','#b6c2d1','#e8eef7','#050506']
  ].map((a,i)=>({id:a[0],num:String(i+1).padStart(2,'0'),name:a[1],primary:a[2],secondary:a[3],hot:a[4],bg:a[5]}));
  const LENSES=[['planet','Planet Scan','AERIS terrain/weather/moons overlay.'],['resonance','Resonance Axis','Vajra hourglass field and polar beam.'],['mandala','Mandala Route','Circular glyph compass and eight-petal waypoints.'],['void','Void Horizon','Filament gravity lens and dark iris.'],['observer','Observer Iris','Eye-shaped scan calibration reticle.'],['archive','Data Horizon','Codex/code-stream accretion and TriFabled archive mode.']].map(a=>({id:a[0],label:a[1],hint:a[2]}));
  const state={profile:0,theme:6,lens:'planet',weather:true,clouds:true,fields:true,open:false,route:false,ready:false};
  const hex=n=>'#'+n.toString(16).padStart(6,'0');
  const css=document.createElement('style');css.textContent=`
    :root{--aeris:#12e6df;--aeris2:#77ffef;--aerisHot:#ffd36d;--aerisBg:#021315;}
    #aerisFx{position:fixed;inset:0;z-index:1;pointer-events:none;mix-blend-mode:screen;opacity:.72;}
    #aerisBar{position:fixed;left:50%;bottom:72px;transform:translateX(-50%);z-index:42;display:flex;align-items:center;gap:8px;padding:7px 9px;border:1px solid rgba(120,245,255,.22);background:rgba(2,7,18,.58);backdrop-filter:blur(16px) saturate(1.4);-webkit-backdrop-filter:blur(16px) saturate(1.4);border-radius:999px;box-shadow:0 14px 60px rgba(0,0,0,.32),0 0 42px color-mix(in srgb,var(--aeris) 14%,transparent);pointer-events:all;font-family:var(--disp);opacity:0;transition:opacity .8s ease .6s;}
    body[data-live="1"] #aerisBar,#ui.live~#aerisBar{opacity:1;}
    #aerisBar button,#aerisPanel button{font-family:inherit;color:inherit;}
    .aerisNudge{width:34px;height:34px;border:1px solid rgba(120,245,255,.2);background:rgba(255,255,255,.04);border-radius:50%;display:grid;place-items:center;cursor:pointer;transition:.18s;}
    .aerisNudge:hover{border-color:var(--aeris);box-shadow:0 0 18px color-mix(in srgb,var(--aeris) 36%,transparent);}
    .aerisCore{display:flex;align-items:center;gap:10px;padding:7px 14px;border-radius:999px;background:linear-gradient(90deg,color-mix(in srgb,var(--aeris) 10%,transparent),rgba(255,255,255,.035));cursor:pointer;min-width:250px;}
    .aerisSig{width:28px;height:28px;border-radius:50%;border:1px solid var(--aeris);box-shadow:inset 0 0 14px color-mix(in srgb,var(--aeris) 45%,transparent),0 0 18px color-mix(in srgb,var(--aeris) 34%,transparent);position:relative;}
    .aerisSig:after{content:"";position:absolute;inset:7px;border-radius:50%;background:var(--aerisHot);box-shadow:0 0 18px var(--aerisHot);}
    .aerisName{font-size:.94rem;font-weight:700;letter-spacing:.22em;color:var(--aeris);line-height:.9;}
    .aerisSub{font-family:var(--mono);font-size:.55rem;letter-spacing:.16em;color:rgba(246,251,255,.64);margin-top:3px;}
    .aerisExplore{padding:10px 17px;border:0;background:linear-gradient(135deg,var(--aeris),color-mix(in srgb,var(--aeris2) 86%,#fff));color:#041014;border-radius:999px;font-weight:800;letter-spacing:.18em;text-transform:uppercase;box-shadow:0 9px 28px color-mix(in srgb,var(--aeris) 25%,transparent);cursor:pointer;}
    #aerisPanel{position:fixed;left:16px;top:148px;width:min(356px,calc(100vw - 32px));max-height:calc(100vh - 244px);overflow:auto;z-index:45;padding:16px;border:1px solid rgba(120,245,255,.18);background:rgba(3,6,16,.74);backdrop-filter:blur(18px) saturate(1.35);-webkit-backdrop-filter:blur(18px) saturate(1.35);box-shadow:0 22px 80px rgba(0,0,0,.38),inset 0 0 0 1px rgba(255,255,255,.03);border-radius:14px;opacity:0;pointer-events:none;transform:translateX(-14px);transition:.28s ease;font-family:var(--mono);}
    #aerisPanel.open{opacity:1;pointer-events:all;transform:none;}
    #aerisPanel::-webkit-scrollbar{width:5px}#aerisPanel::-webkit-scrollbar-thumb{background:rgba(120,245,255,.22);border-radius:4px}
    .apTop{display:flex;align-items:center;gap:10px;border-bottom:1px solid rgba(120,245,255,.12);padding-bottom:12px;margin-bottom:12px}.apLogo{width:38px;height:38px;border-radius:12px;border:1px solid var(--aeris);display:grid;place-items:center;color:var(--aeris);font-size:1.1rem;box-shadow:0 0 24px color-mix(in srgb,var(--aeris) 22%,transparent)}.apTitle{font-family:var(--disp);font-size:1.02rem;font-weight:700;letter-spacing:.28em;color:var(--aeris)}.apK{font-size:.55rem;letter-spacing:.24em;color:rgba(246,251,255,.48);text-transform:uppercase;margin-top:3px}.apX{margin-left:auto;border:0;background:transparent;color:rgba(246,251,255,.55);font-size:1.2rem;cursor:pointer}.apX:hover{color:var(--aerisHot)}
    .aPlanet{display:flex;align-items:center;gap:11px;margin:7px 0;padding:9px;border:1px solid rgba(255,255,255,.07);background:rgba(255,255,255,.035);border-radius:12px;cursor:pointer;transition:.18s}.aPlanet:hover{border-color:color-mix(in srgb,var(--aeris) 38%,transparent);transform:translateX(3px)}.aPlanet.on{border-color:var(--aeris);background:color-mix(in srgb,var(--aeris) 12%,transparent)}.aThumb{width:42px;height:42px;border-radius:50%;box-shadow:inset -8px -6px 15px rgba(0,0,0,.42),0 0 20px color-mix(in srgb,var(--aeris) 18%,transparent)}.aPn{font-family:var(--disp);font-size:.86rem;font-weight:800;letter-spacing:.20em}.aPs{font-size:.58rem;color:rgba(246,251,255,.58);margin-top:2px}.aSel{margin-left:auto;color:var(--aeris);font-size:.68rem;letter-spacing:.14em}
    .apGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px;margin:12px 0}.apStat{padding:8px 9px;border-radius:10px;background:rgba(255,255,255,.035);border:1px solid rgba(255,255,255,.065)}.apStat b{display:block;font-family:var(--disp);font-size:.55rem;letter-spacing:.2em;text-transform:uppercase;color:rgba(246,251,255,.46);margin-bottom:3px}.apStat span{font-size:.72rem;color:rgba(246,251,255,.86)}
    .apMission{display:grid;grid-template-columns:28px 1fr 12px;gap:9px;align-items:center;padding:9px 0;border-top:1px solid rgba(255,255,255,.07)}.apMi{width:28px;height:28px;border-radius:50%;display:grid;place-items:center;background:var(--aeris);color:#061117;font-weight:900}.apMh{font-family:var(--disp);font-size:.72rem;letter-spacing:.18em;font-weight:800}.apMb{font-size:.6rem;color:rgba(246,251,255,.58);line-height:1.45;margin-top:1px}.apArrow{color:rgba(246,251,255,.35)}
    .lensGrid,.themeGrid{display:flex;flex-wrap:wrap;gap:6px;margin:10px 0 13px}.lensBtn,.themeBtn{border:1px solid rgba(120,245,255,.13);background:rgba(255,255,255,.035);border-radius:999px;padding:6px 9px;font-size:.57rem;letter-spacing:.12em;text-transform:uppercase;cursor:pointer}.lensBtn.on,.themeBtn.on{border-color:var(--aeris);background:color-mix(in srgb,var(--aeris) 16%,transparent);color:var(--aerisHot)}.themeBtn i{display:inline-block;width:8px;height:8px;border-radius:50%;margin-right:5px;background:var(--swatch);box-shadow:0 0 10px var(--swatch)}
    .apActions{display:flex;gap:7px}.apActions button{flex:1;padding:9px 8px;border-radius:10px;border:1px solid rgba(120,245,255,.18);background:rgba(255,255,255,.035);font-size:.58rem;letter-spacing:.14em;text-transform:uppercase;cursor:pointer}.apActions button.primary{background:linear-gradient(135deg,var(--aeris),var(--aeris2));color:#061117;font-weight:900}.apNote{margin-top:12px;font-size:.58rem;line-height:1.55;color:rgba(246,251,255,.42)}
    #aerisReticle{position:fixed;left:50%;top:50%;width:42vmin;height:42vmin;transform:translate(-50%,-50%);border-radius:50%;z-index:2;pointer-events:none;opacity:.18;background:radial-gradient(circle,transparent 38%,color-mix(in srgb,var(--aeris) 18%,transparent) 39% 40%,transparent 41%),repeating-conic-gradient(from 0deg,color-mix(in srgb,var(--aeris) 35%,transparent) 0 2deg,transparent 2deg 13deg);filter:drop-shadow(0 0 26px var(--aeris));mix-blend-mode:screen;}
    body[data-aeris-lens="observer"] #aerisReticle{border-radius:50% 0 50% 0;transform:translate(-50%,-50%) rotate(45deg);opacity:.26}body[data-aeris-lens="mandala"] #aerisReticle{opacity:.33}body[data-aeris-lens="planet"] #aerisReticle{opacity:.10}
    @media(max-width:780px){#aerisBar{bottom:96px;max-width:92vw}.aerisCore{min-width:0;padding-right:10px}.aerisName{font-size:.78rem}.aerisExplore{display:none}#aerisPanel{top:88px;max-height:calc(100vh - 206px)}#aerisReticle{width:60vmin;height:60vmin}}
  `;document.head.appendChild(css);

  function hslFromHex(c){try{return new THREE.Color(c).getHex();}catch(e){return 0x12e6df;}}
  function seedFor(p){let h=0;for(let i=0;i<p.id.length;i++)h=(h*33+p.id.charCodeAt(i))>>>0;return h||1;}
  function rnd(seed){let t=seed+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return ((t^t>>>14)>>>0)/4294967296;}
  function makeProfileTexture(p){const w=512,h=256,cv=document.createElement('canvas'),ctx=cv.getContext('2d');cv.width=w;cv.height=h;const pal=p.pal;
    const g=ctx.createLinearGradient(0,0,w,h);pal.forEach((c,i)=>g.addColorStop(i/(pal.length-1),c));ctx.fillStyle=g;ctx.fillRect(0,0,w,h);
    let seed=seedFor(p);ctx.globalCompositeOperation='source-over';
    if(p.fx==='storm'||p.fx==='nyxia'||p.fx==='glacies'||p.fx==='ice'){for(let y=0;y<h;y+=8){const wob=Math.sin(y*.08+seed)*34+Math.sin(y*.17)*11;ctx.globalAlpha=.52;ctx.fillStyle=pal[(Math.floor(y/24)+2)%pal.length];ctx.fillRect(wob,y,w,7+Math.sin(y*.21)*4);}}
    else if(p.fx==='cyber'){ctx.globalAlpha=.38;ctx.strokeStyle=pal[2];ctx.lineWidth=1;for(let x=0;x<w;x+=32){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x+Math.sin(x)*18,h);ctx.stroke();}for(let y=0;y<h;y+=24){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y+Math.sin(y)*9);ctx.stroke();}ctx.globalAlpha=.7;ctx.fillStyle=pal[4];for(let i=0;i<90;i++){ctx.fillRect(rnd(seed+i)*w,rnd(seed+i*2)*h,2+rnd(seed+i*3)*6,1+rnd(seed+i*4)*3);}}
    else if(p.fx==='vajra'){ctx.globalAlpha=.45;ctx.strokeStyle=pal[2];ctx.lineWidth=2;for(let i=0;i<16;i++){const x=w/2+Math.cos(i*Math.PI/8)*w*.22,y=h/2+Math.sin(i*Math.PI/8)*h*.36;ctx.beginPath();ctx.arc(x,y,12+rnd(seed+i)*30,0,Math.PI*2);ctx.stroke();}ctx.globalAlpha=.65;ctx.fillStyle=pal[1];ctx.fillRect(w/2-4,0,8,h);}
    else {for(let i=0;i<520;i++){seed+=i+7;const x=rnd(seed)*w,y=rnd(seed+3)*h,rx=10+rnd(seed+5)*58,ry=4+rnd(seed+9)*24;ctx.globalAlpha=.10+rnd(seed+11)*.28;ctx.fillStyle=pal[Math.floor(rnd(seed+13)*pal.length)];ctx.beginPath();ctx.ellipse(x,y,rx,ry,Math.sin(i)*Math.PI,0,Math.PI*2);ctx.fill();}}
    ctx.globalCompositeOperation='lighter';ctx.globalAlpha=.18;ctx.strokeStyle=pal[5]||'#fff';for(let i=0;i<18;i++){ctx.beginPath();ctx.moveTo(0,rnd(seed+i)*h);ctx.bezierCurveTo(w*.25,rnd(seed+i*3)*h,w*.75,rnd(seed+i*5)*h,w,rnd(seed+i*7)*h);ctx.stroke();}
    const tex=new THREE.CanvasTexture(cv);tex.colorSpace=THREE.SRGBColorSpace;tex.needsUpdate=true;return tex;}

  function makeRing(radius, color, opacity=.55, tilt=.0, squash=.35, seg=260){const pts=[];for(let i=0;i<=seg;i++){const a=i/seg*Math.PI*2;pts.push(new THREE.Vector3(Math.cos(a)*radius,Math.sin(a)*radius*squash,0));}const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color,transparent:true,opacity,blending:THREE.AdditiveBlending,depthWrite:false}));line.rotation.x=Math.PI/2+tilt;return line;}
  function clear(g){if(!g)return;while(g.children.length){const o=g.children.pop();o.traverse?.(m=>{m.geometry&&m.geometry.dispose?.();if(m.material){if(Array.isArray(m.material))m.material.forEach(mm=>mm.dispose?.());else m.material.dispose?.();}});}}
  const AERIS={root:null,moons:null,field:null,weather:null,skin:null,clouds:null,void:null,axis:null,mandala:null,orbitLines:[],moonObjs:[],fxCanvas:null,fx:null,t:0};window.AERIS=AERIS;
  function buildObjects(){if(AERIS.root||!window.THREE||typeof scene==='undefined'||!scene||typeof PLANET_R==='undefined')return;AERIS.root=new THREE.Group();AERIS.root.name='AERIS Cosmic Scanner';scene.add(AERIS.root);AERIS.moons=new THREE.Group();AERIS.field=new THREE.Group();AERIS.axis=new THREE.Group();AERIS.mandala=new THREE.Group();AERIS.void=new THREE.Group();AERIS.root.add(AERIS.moons,AERIS.field,AERIS.axis,AERIS.mandala,AERIS.void);
    const shellGeo=new THREE.SphereGeometry(PLANET_R*1.014,96,48);AERIS.skin=new THREE.Mesh(shellGeo,new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.23,depthWrite:false,blending:THREE.AdditiveBlending}));AERIS.root.add(AERIS.skin);
    AERIS.clouds=new THREE.Mesh(new THREE.SphereGeometry(PLANET_R*1.045,64,36),new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.13,depthWrite:false,blending:THREE.AdditiveBlending,wireframe:true}));AERIS.root.add(AERIS.clouds);
    // Vajra axis field: vertical beam + polar torus crowns
    const beam=new THREE.Mesh(new THREE.CylinderGeometry(.06,.06,PLANET_R*3.6,16,1,true),new THREE.MeshBasicMaterial({color:0xfff4c4,transparent:true,opacity:.48,blending:THREE.AdditiveBlending,depthWrite:false}));beam.rotation.z=0;AERIS.axis.add(beam);
    for(const y of[-PLANET_R*1.25,PLANET_R*1.25]){const tor=new THREE.Mesh(new THREE.TorusGeometry(PLANET_R*.46,.025,8,96),new THREE.MeshBasicMaterial({color:0xfff1b5,transparent:true,opacity:.6,blending:THREE.AdditiveBlending,depthWrite:false}));tor.position.y=y;tor.rotation.x=Math.PI/2;AERIS.axis.add(tor);}for(let i=0;i<18;i++){const line=makeRing(PLANET_R*(.7+i*.04),0xfff3c0,.12,.2+i*.09,.18,128);line.rotation.z=i*.25;AERIS.axis.add(line);}
    // Mandala route: concentric compass + 8 petals
    for(let r of[.62,.78,.96,1.14,1.33])AERIS.mandala.add(makeRing(PLANET_R*r,0xffffff,.18+r*.13,.0,.06,240));for(let i=0;i<8;i++){const a=i*Math.PI/4;const petal=new THREE.Mesh(new THREE.TorusGeometry(PLANET_R*.11,.018,6,40),new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.48,blending:THREE.AdditiveBlending,depthWrite:false}));petal.position.set(Math.cos(a)*PLANET_R*1.18,0,Math.sin(a)*PLANET_R*1.18);petal.scale.set(1.0,1.8,1);petal.rotation.y=-a;petal.rotation.x=Math.PI/2;AERIS.mandala.add(petal);}
    // Void/iris: black center, filament rings, code accretion plane
    const iris=new THREE.Mesh(new THREE.TorusGeometry(PLANET_R*1.45,.05,10,160),new THREE.MeshBasicMaterial({color:0xcfe3ff,transparent:true,opacity:.45,blending:THREE.AdditiveBlending,depthWrite:false}));iris.rotation.x=Math.PI/2;AERIS.void.add(iris);const black=new THREE.Mesh(new THREE.SphereGeometry(PLANET_R*.35,40,20),new THREE.MeshBasicMaterial({color:0x000000,transparent:true,opacity:.82,depthWrite:false}));black.position.set(0,0,-PLANET_R*1.7);AERIS.void.add(black);for(let i=0;i<36;i++){const l=makeRing(PLANET_R*(1.15+rnd(i)*.75),0xbfd7ff,.06+rnd(i+9)*.2,(rnd(i+3)-.5)*1.2,.12+rnd(i+4)*.4,80);l.rotation.z=rnd(i+5)*Math.PI;AERIS.void.add(l);}
    buildWeather();makeFxCanvas();applyProfile(0,true);tick();}
  function buildWeather(){if(!AERIS.root)return;if(AERIS.weather){AERIS.root.remove(AERIS.weather);AERIS.weather.geometry.dispose();AERIS.weather.material.dispose();}const N=520,arr=new Float32Array(N*3),cols=new Float32Array(N*3),p=AERIS_PLANETS[state.profile];for(let i=0;i<N;i++){const z=2*rnd(i*4+2)-1,a=rnd(i*7+5)*Math.PI*2,r=(PLANET_R*(1.08+rnd(i+8)*.42));const q=Math.sqrt(1-z*z);arr[i*3]=Math.cos(a)*q*r;arr[i*3+1]=z*r;arr[i*3+2]=Math.sin(a)*q*r;const c=new THREE.Color(p.pal[i%p.pal.length]);cols[i*3]=c.r;cols[i*3+1]=c.g;cols[i*3+2]=c.b;}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(arr,3));geo.setAttribute('color',new THREE.BufferAttribute(cols,3));AERIS.weather=new THREE.Points(geo,new THREE.PointsMaterial({size:.18,vertexColors:true,transparent:true,opacity:.58,blending:THREE.AdditiveBlending,depthWrite:false}));AERIS.root.add(AERIS.weather);}
  function applyProfile(i,quiet=false){state.profile=(i+AERIS_PLANETS.length)%AERIS_PLANETS.length;const p=AERIS_PLANETS[state.profile],t=AERIS_THEMES[state.theme];document.documentElement.style.setProperty('--aeris',t.primary);document.documentElement.style.setProperty('--aeris2',t.secondary);document.documentElement.style.setProperty('--aerisHot',t.hot);document.documentElement.style.setProperty('--aerisBg',t.bg);document.body.dataset.aerisPlanet=p.id;document.body.dataset.aerisLens=state.lens;
    if(AERIS.skin){AERIS.skin.material.map&&AERIS.skin.material.map.dispose?.();AERIS.skin.material.map=makeProfileTexture(p);AERIS.skin.material.color.set(0xffffff);AERIS.skin.material.opacity=(p.fx==='cyber'||p.fx==='vajra')?0.30:0.22;AERIS.skin.rotation.z=p.tilt;AERIS.clouds.material.color.set(hslFromHex(p.pal[2]||t.secondary));AERIS.clouds.material.opacity=state.clouds?0.16:0;}
    if(AERIS.field){clear(AERIS.field);AERIS.orbitLines=[];const base=PLANET_R*1.33;for(let k=0;k<7;k++){const line=makeRing(base+k*PLANET_R*.08,hslFromHex(k%2?p.pal[1]:p.pal[2]||t.primary),.28-k*.018,p.tilt*.25+k*.12,.32+k*.045,240);line.rotation.z=k*.42;AERIS.field.add(line);AERIS.orbitLines.push(line);}if(p.rings){for(let k=0;k<5;k++){const line=makeRing(PLANET_R*(1.11+k*.04),hslFromHex(p.ring||p.pal[1]),.32-k*.03,p.tilt+.05*k,.08,260);line.rotation.z=k*.23;AERIS.field.add(line);AERIS.orbitLines.push(line);}}}
    if(AERIS.moons){clear(AERIS.moons);AERIS.moonObjs=[];(p.moonsData||[]).forEach((m,idx)=>{const hold=new THREE.Group();const a=idx*Math.PI*2/Math.max(1,p.moonsData.length);hold.rotation.z=a;const mesh=new THREE.Mesh(new THREE.SphereGeometry(PLANET_R*m[2],20,14),new THREE.MeshToonMaterial({color:hslFromHex(m[4]),gradientMap:typeof toonRamp!=='undefined'?toonRamp:null}));mesh.position.x=PLANET_R*m[1];const glow=new THREE.Mesh(new THREE.SphereGeometry(PLANET_R*m[2]*1.25,16,10),new THREE.MeshBasicMaterial({color:hslFromHex(m[4]),transparent:true,opacity:.14,blending:THREE.AdditiveBlending,depthWrite:false}));glow.position.copy(mesh.position);hold.add(mesh,glow);AERIS.moons.add(hold);AERIS.moonObjs.push({hold,mesh,period:m[3],off:a});});}
    if(AERIS.weather)buildWeather();
    try{if(planet&&planet.userData){const surface=planet.userData.surface;if(surface&&surface.material&&surface.material.color)surface.material.color.set(hslFromHex(p.pal[3]||'#ffffff'));if(planet.userData.atmo){planet.userData.atmo.material.uniforms.color.value.set(hslFromHex(t.primary));planet.userData.atmo.material.uniforms.intensity.value=.48;}if(planet.userData.atmo2){planet.userData.atmo2.material.uniforms.color.value.set(hslFromHex(t.secondary));}}}catch(e){}
    try{if(scene&&scene.fog)scene.fog.color.lerp(new THREE.Color(t.bg),.25);if(bloomPass)bloomPass.strength=Math.max(bloomPass.strength||0,.28);if(window._painterlyPass&&_painterlyPass.uniforms){_painterlyPass.uniforms.uWarm.value=(state.theme===3?.075:state.theme===4?.04:.03);_painterlyPass.uniforms.uGrain.value=(p.fx==='cyber'?.024:p.fx==='void'?.055:.038);}}catch(e){}
    renderPanel();updateBar();if(!quiet&&typeof banner==='function')banner('AERIS Scan Profile',`${p.name} · ${p.sub} — ${p.weather}`);}
  function setTheme(i){state.theme=(i+AERIS_THEMES.length)%AERIS_THEMES.length;applyProfile(state.profile,true);renderPanel();if(typeof banner==='function')banner('Theme Lab',`${AERIS_THEMES[state.theme].num} · ${AERIS_THEMES[state.theme].name}`);}
  function setLens(id){state.lens=id;document.body.dataset.aerisLens=id;try{AERIS.axis.visible=id==='resonance'||id==='archive';AERIS.mandala.visible=id==='mandala'||state.route;AERIS.void.visible=id==='void'||id==='observer'||id==='archive';AERIS.field.visible=state.fields;AERIS.skin.visible=id!=='void';AERIS.clouds.visible=state.clouds;}catch(e){}renderPanel();if(typeof banner==='function')banner('AERIS Lens',`${LENSES.find(l=>l.id===id)?.label||id}`);}
  function togglePanel(force){state.open=force!==undefined?force:!state.open;const p=document.getElementById('aerisPanel');if(p)p.classList.toggle('open',state.open);}
  function renderPanel(){const el=document.getElementById('aerisPanel');if(!el)return;const p=AERIS_PLANETS[state.profile];const theme=AERIS_THEMES[state.theme];el.innerHTML=`<div class="apTop"><div class="apLogo">◉</div><div><div class="apTitle">AERIS SCANNER</div><div class="apK">${p.sector} · ${p.realm} · lens ${state.lens}</div></div><button class="apX" data-close>×</button></div>
    <div class="apGrid"><div class="apStat"><b>Gravity</b><span>${p.gravity}</span></div><div class="apStat"><b>Atmosphere</b><span>${p.atm}</span></div><div class="apStat"><b>Surface Temp</b><span>${p.temp}</span></div><div class="apStat"><b>Magnetic</b><span>${p.mag}</span></div><div class="apStat"><b>Moon Count</b><span>${p.moons}</span></div><div class="apStat"><b>Difficulty</b><span>${p.diff}</span></div></div>
    <div class="apK">PLANET CATALOG</div><div>${AERIS_PLANETS.map((q,i)=>`<div class="aPlanet ${i===state.profile?'on':''}" data-planet="${i}"><div class="aThumb" style="background:radial-gradient(circle at 32% 28%,${q.pal[5]||'#fff'},${q.pal[2]} 28%,${q.pal[1]} 55%,${q.pal[0]})"></div><div><div class="aPn">${q.name}</div><div class="aPs">${q.sub}</div></div><div class="aSel">${i===state.profile?'ACTIVE':''}</div></div>`).join('')}</div>
    <div class="apK">LENSES</div><div class="lensGrid">${LENSES.map(l=>`<button class="lensBtn ${l.id===state.lens?'on':''}" data-lens="${l.id}" title="${l.hint}">${l.label}</button>`).join('')}</div>
    <div class="apK">SPIRAL THEME LAB</div><div class="themeGrid">${AERIS_THEMES.map((q,i)=>`<button class="themeBtn ${i===state.theme?'on':''}" data-theme="${i}"><i style="--swatch:${q.primary}"></i>${q.num}</button>`).join('')}</div>
    <div class="apK">HIGHLIGHTS & MISSIONS</div><div>${p.missions.map(m=>`<div class="apMission"><div class="apMi">${m[0]}</div><div><div class="apMh">${m[1]}</div><div class="apMb">${m[2]}</div></div><div class="apArrow">›</div></div>`).join('')}</div>
    <div class="apActions"><button data-weather>${state.weather?'Weather ON':'Weather OFF'}</button><button data-clouds>${state.clouds?'Clouds ON':'Clouds OFF'}</button><button data-route class="primary">${state.route?'Route Locked':'Route'}</button></div>
    <div class="apNote"><b>${theme.name}</b> maps the new spiral-background photo set into a live palette. ${p.name} maps the earlier AERIS sphere references onto the current walkable TriFable planet without destroying courier gameplay.</div>`;
    el.querySelector('[data-close]')?.addEventListener('click',()=>togglePanel(false));el.querySelectorAll('[data-planet]').forEach(b=>b.onclick=()=>applyProfile(+b.dataset.planet));el.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>setTheme(+b.dataset.theme));el.querySelectorAll('[data-lens]').forEach(b=>b.onclick=()=>setLens(b.dataset.lens));el.querySelector('[data-weather]')?.addEventListener('click',()=>{state.weather=!state.weather;if(AERIS.weather)AERIS.weather.visible=state.weather;renderPanel();});el.querySelector('[data-clouds]')?.addEventListener('click',()=>{state.clouds=!state.clouds;if(AERIS.clouds)AERIS.clouds.visible=state.clouds;renderPanel();});el.querySelector('[data-route]')?.addEventListener('click',()=>{state.route=!state.route;setLens(state.route?'mandala':state.lens);renderPanel();});}
  function updateBar(){const b=document.getElementById('aerisBar');if(!b)return;const p=AERIS_PLANETS[state.profile];b.querySelector('.aerisName').textContent=p.name;b.querySelector('.aerisSub').textContent=`${p.sub} · ${p.moons} moons · ${state.lens}`;}
  function mountUI(){if(document.getElementById('aerisBar'))return;const ret=document.createElement('div');ret.id='aerisReticle';document.body.appendChild(ret);const panel=document.createElement('div');panel.id='aerisPanel';document.body.appendChild(panel);const bar=document.createElement('div');bar.id='aerisBar';bar.innerHTML=`<button class="aerisNudge" data-prev>‹</button><div class="aerisCore" data-open><div class="aerisSig"></div><div><div class="aerisName">AERIS</div><div class="aerisSub">planetary scanner</div></div></div><button class="aerisExplore" data-explore>Explore</button><button class="aerisNudge" data-next>›</button>`;document.body.appendChild(bar);
    bar.querySelector('[data-open]').onclick=()=>togglePanel();bar.querySelector('[data-explore]').onclick=()=>{togglePanel(true);setLens(state.lens==='planet'?'resonance':state.lens);};bar.querySelector('[data-prev]').onclick=()=>applyProfile(state.profile-1);bar.querySelector('[data-next]').onclick=()=>applyProfile(state.profile+1);
    const rail=document.getElementById('rail');if(rail&&!document.getElementById('aerisRailBtn')){const btn=document.createElement('button');btn.className='rbtn';btn.id='aerisRailBtn';btn.innerHTML='🪐<span class="tip">AERIS</span>';btn.onclick=()=>togglePanel();rail.insertBefore(btn,rail.firstChild);}document.addEventListener('keydown',e=>{if(e.code==='KeyP'){togglePanel();}if(e.code==='BracketRight'){applyProfile(state.profile+1);}if(e.code==='BracketLeft'){applyProfile(state.profile-1);}if(e.code==='KeyL'){const i=Math.max(0,LENSES.findIndex(l=>l.id===state.lens));setLens(LENSES[(i+1)%LENSES.length].id);}if(e.code==='KeyT'&&e.altKey){setTheme(state.theme+1);}});renderPanel();updateBar();}
  function augmentCodex(){try{const body=document.getElementById('codexBody');if(body&&!document.getElementById('aerisCodexBlock')){const div=document.createElement('div');div.id='aerisCodexBlock';div.innerHTML=`<div class="lore"><h3>AERIS Planetary Scanner</h3><p>The AERIS layer translates the earlier pale glass planet explorer into this dark TriFable VerseGate: scan profiles tint the walkable sphere, spawn moons/rings/weather, and retain the courier mission loop.</p></div><div class="lore"><h3>Cosmic Lenses</h3><p>Resonance Axis maps the Vajra/hourglass references; Mandala Route maps the glyph wheel and eight petals; Void Horizon maps the black-hole filament field; Observer Iris maps the eye reticle; Data Horizon maps code-stream accretion.</p></div>`;body.appendChild(div);}}catch(e){}}
  function augmentForge(){try{const old=window.TriForge&&window.TriForge.fillForge;if(!old||window.TriForge._aerisWrapped)return;window.TriForge.fillForge=function(){old.apply(this,arguments);const body=document.getElementById('forgeBody');if(body&&!document.getElementById('aerisForgeBlock')){const box=document.createElement('div');box.id='aerisForgeBlock';box.className='forge-harness';box.innerHTML=`<div class="fh-h">AERIS Extension <span>planet scanner bridge</span></div><div class="fh-row"><b>New capability:</b> <code>planetary_scan_lens</code> connects profile selection, terrain tint, weather particles, moons, route mandala and theme lab.</div><div class="fh-int"><span>Three.js overlays</span><span>procedural texture</span><span>single-file runtime</span><span>dark spiral themes</span></div>`;body.appendChild(box);}};window.TriForge._aerisWrapped=true;}catch(e){}}
  function makeFxCanvas(){if(AERIS.fxCanvas)return;const cv=document.createElement('canvas');cv.id='aerisFx';document.body.insertBefore(cv,document.getElementById('ui'));AERIS.fxCanvas=cv;AERIS.fx=cv.getContext('2d');const resize=()=>{cv.width=innerWidth*Math.min(devicePixelRatio||1,2);cv.height=innerHeight*Math.min(devicePixelRatio||1,2);cv.style.width=innerWidth+'px';cv.style.height=innerHeight+'px';};resize();addEventListener('resize',resize);}
  function drawFx(){const cv=AERIS.fxCanvas,ctx=AERIS.fx;if(!cv||!ctx)return;const dpr=cv.width/Math.max(1,innerWidth),w=cv.width,h=cv.height,p=AERIS_PLANETS[state.profile],t=AERIS_THEMES[state.theme];ctx.clearRect(0,0,w,h);ctx.save();ctx.scale(dpr,dpr);ctx.globalCompositeOperation='screen';const time=AERIS.t;
    const g=ctx.createRadialGradient(innerWidth*.55,innerHeight*.42,10,innerWidth*.5,innerHeight*.5,Math.max(innerWidth,innerHeight)*.68);g.addColorStop(0,t.primary+'33');g.addColorStop(.32,'transparent');g.addColorStop(1,t.secondary+'10');ctx.fillStyle=g;ctx.fillRect(0,0,innerWidth,innerHeight);
    ctx.globalAlpha=(state.lens==='archive'||state.lens==='void')?0.28:0.14;ctx.strokeStyle=t.secondary;ctx.lineWidth=1;for(let i=0;i<36;i++){const y=(i*47+time*18)%innerHeight;ctx.beginPath();ctx.moveTo(0,y);for(let x=0;x<innerWidth;x+=90){ctx.lineTo(x,y+Math.sin(x*.008+time+i)*18);}ctx.stroke();}
    if(state.lens==='archive'){ctx.globalAlpha=.22;ctx.font='10px JetBrains Mono,monospace';ctx.fillStyle=t.secondary;for(let i=0;i<48;i++){const x=(i*73+time*36)%innerWidth,y=(i*31+time*22)%innerHeight;ctx.fillText(['{route:true}','scan.active','φ=∫e^iθ','planet.mesh','agent.link','AERIS.OS'][i%6],x,y);}}
    if(state.lens==='observer'){ctx.globalAlpha=.28;ctx.strokeStyle=t.hot;ctx.lineWidth=1.5;ctx.beginPath();ctx.ellipse(innerWidth/2,innerHeight/2,innerWidth*.18,innerHeight*.11,0,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(innerWidth/2,innerHeight/2,Math.min(innerWidth,innerHeight)*.045,0,Math.PI*2);ctx.stroke();}
    ctx.restore();}
  function tick(now){AERIS.t=(now||performance.now())*.001;const p=AERIS_PLANETS[state.profile];try{if(AERIS.root){AERIS.root.visible=true;if(AERIS.skin){AERIS.skin.rotation.y+=p.spin*.002;AERIS.skin.rotation.x=Math.sin(AERIS.t*.27)*.015;}if(AERIS.clouds){AERIS.clouds.rotation.y-=p.spin*.0016;AERIS.clouds.visible=state.clouds;}if(AERIS.weather){AERIS.weather.visible=state.weather;AERIS.weather.rotation.y+=.001+(p.fx==='storm'?.002:.0);AERIS.weather.rotation.x=Math.sin(AERIS.t*.3)*.03;}AERIS.orbitLines.forEach((l,i)=>{l.rotation.z+=.0007+i*.00008;});AERIS.moonObjs.forEach((m,i)=>{m.hold.rotation.y=AERIS.t*Math.PI*2/m.period+m.off;m.mesh.rotation.y+=.006;});if(AERIS.axis)AERIS.axis.rotation.y+=.0022;if(AERIS.mandala)AERIS.mandala.rotation.y-=.0012;if(AERIS.void)AERIS.void.rotation.z+=.0008;}}catch(e){}drawFx();requestAnimationFrame(tick);}
  const prevInit=window.init;window.init=async function(){const out=await prevInit.apply(this,arguments);try{mountUI();buildObjects();augmentCodex();augmentForge();setLens('planet');document.body.dataset.aeris='1';}catch(e){console.warn('[AERIS] upgrade skipped:',e);}return out;};
})();
